#!/bin/sh
#
#	ecoff-cmp file1.o file2.o
#
TMP="${TMP-/tmp}"
cp $1 $TMP/foo1.$$
cp $2 $TMP/foo2.$$
strip $TMP/foo1.$$
strip $TMP/foo2.$$
tail +10c $TMP/foo1.$$ > $TMP/foo3.$$
tail +10c $TMP/foo2.$$ > $TMP/foo4.$$
cmp $TMP/foo3.$$ $TMP/foo4.$$
rm -f $TMP/foo[1234].$$
